# https://packaging.python.org/en/latest/specifications/declaring-project-metadata/
# https://packaging.python.org/en/latest/tutorials/packaging-projects/

[build-system]
requires = ['hatchling', 'hatch-vcs', 'wheel']
build-backend = 'hatchling.build'

[project]
name = 'mlfcs'
description = 'A library for analysing SPT data to do molecular dynamic estimations (estimation of diffusion coefficient,anomalous exponent,...).'
license = {file = 'LICENSE.txt'}
dependencies = [
  'numpy',
  'pandas',
  'scipy',
  'sklearn',
  'ptu',
  'matplotlib',
  'seaborn',
  'yaml'
]
authors = [
  {name = 'Nathan Quiblier', email = 'nathan.quiblier@inria.fr' }
]
requires-python = '>=3.6'
# https://pypi.org/classifiers/
classifiers = [
  'Operating System :: OS Independent',
  'Programming Language :: Python :: 3'
]
readme = 'README.md'
dynamic = ['version']

[project.urls]
Source = 'https://gitlab.inria.fr/nquilbie/sptoolbox'
Documentation = 'https://gitlab.inria.fr/nquilbie/sptoolbox'

# Set the version from Git.
[tool.hatch.version]
source = 'vcs'

[tool.hatch.version.raw-options]
version_scheme = 'no-guess-dev'
local_scheme = 'no-local-version'

[tool.hatch.build.hooks.vcs]
version-file = 'src/sptools/version.py'
template = """\
#!/usr/bin/env python3
'''
Version file automatically generated by setuptools-scm via hatch-vcs.
https://pypi.org/project/setuptools-scm/
https://github.com/ofek/hatch-vcs
Do not track this file and do not edit it manually.
'''
VERSION = {version!r}
VERSION_TUPLE = {version_tuple!r}
"""

[tool.pylint.'MESSAGES CONTROL']
max-line-length = 100
